### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'api-key.json'

### ISSUE THREAD

**Issue by sudodoit** [mansi1710/DobaraMatPuchana#3]
i have cloned the repository and then installed the requirements and then tried to run main.py and I was getting the following error. 
![image](https://user-images.githubusercontent.com/63787324/82846523-dc212000-9f06-11ea-8360-aa4b8a0aa9c9.png)
`Traceback (most recent call last):
  File "main.py", line 16, in <module>
    engine = speech.speech_to_text()
  File "/home/vinay/DobaraMatPuchana/speech.py", line 22, in __init__
    self.credentials = service_account.Credentials.from_service_account_file('api-key.json')
  File "/home/vinay/.local/lib/python3.6/site-packages/google/oauth2/service_account.py", line 218, in from_service_account_file
    filename, require=["client_email", "token_uri"]
  File "/home/vinay/.local/lib/python3.6/site-packages/google/auth/_service_account_info.py", line 72, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'api-key.json'
`
This was the error and could you please help me in solving this error. It would be a great help for me. 
Thanks

**Comment by mansi1710** [comment]
Regarding the above issue, you will have to download the credentials for Google Vision API which is unique for every account. The downloaded json file should be pasted at the required location.

**Comment by sudodoit** [comment]
Thank you soo much
